### ISSUE TITLE
Compilation : include / include_lib

### ISSUE THREAD

**Issue by pgourlain** [pgourlain/vscode_erlang#13]
Message from 'https://marketplace.visualstudio.com/items?itemName=pgourlain.erlang'

-include(). and 
-include_lib() does not work properly.. 

To make it work i need to specify complete path with respect to current file.. it does not look into include dir... but rebar works fine..

**Comment by pgourlain** [comment]
no feedback : considered resolved

**Comment by Katur7** [comment]
I'm having this issue.

I have a project that is using amqp_client from [github.com/jbrisbin/amqp_client](github.com/jbrisbin/amqp_client) to connect to a RabbitMQ queue.
To connect to the queue I have to import header files from the library, that is done like this:
```
-include_lib("amqp_client/include/amqp_client.hrl").
```
This compiles just fine using rebar3 but I get a lot of errors in VSCode for example:
* can't find include_lib "amqp_client/include/amqp_client.hrl"
* record amqp_params_network undefined
* record undefined for the rest of the amqp imported records

**Comment by Katur7** [comment]
@pgourlain 
I'm not sure if you saw my earlier comment.
Can this issue be reopened? Is there any more info I can provide?

**Comment by andreabenini** [comment]
Same problem here.
I have disabled linters or additional erlang modules to avoid interferences but I can see these kind of errors:
```
[erl] behaviour gen_mod undefined
[erl] function init/1 undefined
[erl] spec for undefined function start/2
[erl] record xmlel undefined
[erl] variable 'Total' is unused    (when it's not true because I'm using it below)
```
My module compiles gracefully but I can still see red or green lines in vscode when using it. I can minify some code and produce a short module (this file is about 2k lines) if this helps

**Comment by wojteksurowka** [comment]
@andreabenini can you test in the version 0.2.9 please? The problem should be fixed there.

**Comment by andreabenini** [comment]
I'm now using v0.3.0 from VSCode marketplace.  I'm still getting this kind of error:
`[erl] can't find include file "logger.hrl"`
even if I have
```
    // Directory location of erl/escript.
    "erlang.erlangPath": "/opt/ejabberd/lib/ejabberd-<version>/include/"
```
in what it's supposed to be (I guess, not sure btw) the include search path. I don't have a rebar script and I'm trying to get absolute paths from my local filesystem.
Tried to use `/opt/ejabberd/lib/**` but even real and absolute paths, is there a way to include .hrl files that are not located in the current dir ?

Thanks again for this awesome plugin

**Comment by wojteksurowka** [comment]
@andreabenini can you provide more details please:
- how do you build your sources, I assume that build is successful. Do you use rebar3 or rebar? Can you share your rebar.config if so?
- the include line in the source - is it just a Gina name or any oath is there 
The erlpath setting is for erl location not include files. The extension gets include path from rebar.config.

**Comment by andreabenini** [comment]
I don't have a standalone project and I'm building an ejabberd module with ProcessOne stuff and paths.
I'm not controlling any environment variable and I don't have control on rebar config. I'm simply using ejabberd build module utility, that produces a valid .beam file from there. [ejabberdctl install_module] 
I was looking for some kind of include path somewhere in your config to avoid editor warnings, something like other plugins already do (C++ for example).
I can create a dummy rebar.config for the project if this could solve these warnings and insert some path from there (or if you've a working skeleton I can use that).
I'm probably missing the point or using your plugin in a different way

Thanks
Ben

**Comment by wojteksurowka** [comment]
@andreabenini understood. Your case is indeed not supported in the current version. As you proposed I will add a config entry for such cases as this one. For now you can create a dummy rebar.config with i entry in erl_opts, or you temporarily disable linting.

**Comment by wojteksurowka** [comment]
@andreabenini in version 0.3.2 you can use the new setting erlang.includePaths to set a custom include path. Can you try it and confirm if it fixes the problem you raised please?

**Comment by andreabenini** [comment]
Downloaded and tested. .includePaths option is a really nice addon.
After few minutes and tests I cannot understand (yet) if wildcards might work with it, but absolute and static paths are fine.
This works:
` "erlang.includePaths": ["/opt/ejabberd/lib/ejabberd/include/"],`
This doesn't work:
` "erlang.includePaths": ["/opt/ejabberd/lib/**/*"],`
That's because this huge project (ejabberd) has a tree like that:
```
./lib/ejabberd/include/*
./lib/fastxml/include/*
...
```
and I want to include them all in once, adding each single dir at a time is enough for me even if I'm trying random combinations of `*`, `**`, `**/*`, `**/include/`... and so on. I'll tell you how it goes, but btw this is a nice addon for me. You can close this issue if you wish.
Congratulations

**Comment by wojteksurowka** [comment]
Thank you! The issue can be closed.
